# Generated by Django 5.1.7 on 2025-03-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_category_slug_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='attribute_key_id',
            new_name='attribute_key',
        ),
        migrations.RenameField(
            model_name='productattribute',
            old_name='attribute_value_id',
            new_name='attribute_value',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
