# Generated by Django 5.1.7 on 2025-03-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_attribute_key_id_productattribute_attribute_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vat_number',
            field=models.CharField(blank=True, max_length=9, unique=True),
        ),
    ]
